Repository jenkinsci/build-failure-analyzer-plugin, pull requests merged in 2019-10, with the labels that each got.

#112 [JENKINS-59610 JENKINS-59593] Fixed configuration issues introduced in 1.23
  src/main/java/com/sonyericsson/jenkins/plugins/bfa/BuildFailureScanner.java
  src/main/java/com/sonyericsson/jenkins/plugins/bfa/PluginImpl.java
  src/main/java/com/sonyericsson/jenkins/plugins/bfa/db/KnowledgeBase.java
  src/main/java/com/sonyericsson/jenkins/plugins/bfa/db/LocalFileKnowledgeBase.java
  src/main/java/com/sonyericsson/jenkins/plugins/bfa/db/MongoDBKnowledgeBase.java
  src/main/java/com/sonyericsson/jenkins/plugins/bfa/statistics/StatisticsLogger.java
  src/main/resources/com/sonyericsson/jenkins/plugins/bfa/CauseManagement/index.groovy
  src/main/resources/com/sonyericsson/jenkins/plugins/bfa/db/MongoDBKnowledgeBase/config.jelly
  src/test/java/com/sonyericsson/jenkins/plugins/bfa/BuildFailureScannerHudsonTest.java
  src/test/java/com/sonyericsson/jenkins/plugins/bfa/CauseManagementHudsonTest.java
  src/test/java/com/sonyericsson/jenkins/plugins/bfa/PluginImplHudsonTest.java
  src/test/java/com/sonyericsson/jenkins/plugins/bfa/jcasc/ConfigurationAsCodeMongoTest.java
Labels: regression

#114 Bump jackson2 to 2.10.0
  pom.xml
  src/test/java/com/sonyericsson/jenkins/plugins/bfa/PluginImplHudsonTest.java
Labels: dependencies

#116 stop the MongoDB processes forked in tests
  src/test/java/com/sonyericsson/jenkins/plugins/bfa/db/EmbeddedMongoTest.java
Labels: chore

#115 Fix boolean options in plugin global config
  src/main/java/com/sonyericsson/jenkins/plugins/bfa/PluginImpl.java
  src/test/java/com/sonyericsson/jenkins/plugins/bfa/PluginImplHudsonTest.java
Labels: regression

#117 Add a global switch to disable report when no causes identified (PR #79 resurrection)
  src/main/java/com/sonyericsson/jenkins/plugins/bfa/PluginImpl.java
  src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/FailureCauseDisplayData.java
  src/main/resources/com/sonyericsson/jenkins/plugins/bfa/PluginImpl/config.jelly
  src/main/resources/com/sonyericsson/jenkins/plugins/bfa/model/FailureCauseBuildAction/summary.groovy
  src/main/resources/com/sonyericsson/jenkins/plugins/bfa/model/FailureCauseMatrixBuildAction/summary.groovy
  src/test/java/com/sonyericsson/jenkins/plugins/bfa/BuildFailureScannerHudsonTest.java
  src/test/java/com/sonyericsson/jenkins/plugins/bfa/PluginImplHudsonTest.java
  src/test/java/com/sonyericsson/jenkins/plugins/bfa/TransientCauseManagementHudsonTest.java
  src/test/java/com/sonyericsson/jenkins/plugins/bfa/sod/ScanOnDemandBaseActionTest.java
  src/test/resources/com/sonyericsson/jenkins/plugins/bfa/jcasc/jcasc-local-expected.yml
  src/test/resources/com/sonyericsson/jenkins/plugins/bfa/jcasc/jcasc-local.yml
  src/test/resources/com/sonyericsson/jenkins/plugins/bfa/jcasc/jcasc-mongo-expected.yml
  src/test/resources/com/sonyericsson/jenkins/plugins/bfa/jcasc/jcasc-mongo.yml
Labels: enhancement

#118 Fixed some missed data binding annotations in global config
  src/main/java/com/sonyericsson/jenkins/plugins/bfa/PluginImpl.java
Labels: chore, regression
