Repository jenkinsci/build-failure-analyzer-plugin, pull requests merged in 2020-01, with the labels that each got.

#120 Upgrade parent pom
  pom.xml
  src/test/java/com/sonyericsson/jenkins/plugins/bfa/BuildFailureScannerHudsonTest.java
Labels: chore

#125 bump jackson2-api to 2.10.2
  pom.xml
Labels: dependencies

#123 Cleanup pom.xml
  pom.xml
Labels: chore

#121 Include line number of the found indication data
  src/main/java/com/sonyericsson/jenkins/plugins/bfa/db/MongoDBKnowledgeBase.java
  src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/FailureReader.java
  src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/indication/FoundIndication.java
  src/main/java/com/sonyericsson/jenkins/plugins/bfa/providers/FailureCauseProvider.java
  src/test/java/com/sonyericsson/jenkins/plugins/bfa/FailureCauseProviderTest.java
Labels: enhancement

#124 fix jcasc test harness
  pom.xml
Labels: dependencies
