Repository jenkinsci/build-failure-analyzer-plugin, pull requests merged in 2021-09, with the labels that each got.

#145 Fix FailureCause constructor not passing comment argument
  src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/FailureCause.java
Labels: bug

#141 Integration with the Metrics plugin
  README.md
  docs/metrics.md
  pom.xml
  src/main/java/com/sonyericsson/jenkins/plugins/bfa/BuildFailureScanner.java
  src/main/java/com/sonyericsson/jenkins/plugins/bfa/MetricsManager.java
  src/main/java/com/sonyericsson/jenkins/plugins/bfa/db/LocalFileKnowledgeBase.java
  src/main/java/com/sonyericsson/jenkins/plugins/bfa/db/MongoDBKnowledgeBase.java
  src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/FailureCause.java
  src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/FoundFailureCause.java
  src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/IFailureCauseMetricData.java
  src/test/java/com/sonyericsson/jenkins/plugins/bfa/MetricsManagerTest.java
  src/test/java/com/sonyericsson/jenkins/plugins/bfa/db/LocalFileKnowledgeBaseTest.java
  src/test/java/com/sonyericsson/jenkins/plugins/bfa/db/MongoDBKnowledgeBaseTest.java
  src/test/java/com/sonyericsson/jenkins/plugins/bfa/model/FailureCauseTest.java
  src/test/java/com/sonyericsson/jenkins/plugins/bfa/sod/ScanOnDemandTaskTest.java
Labels: enhancement

#146 Configure BOM
  pom.xml
  src/test/java/com/sonyericsson/jenkins/plugins/bfa/PluginImplHudsonTest.java
Labels: chore
