Repository jenkinsci/build-failure-analyzer-plugin, pull requests merged in 2022-05, with the labels that each got.

#155 Adapt icon removal from core
  src/main/resources/com/sonyericsson/jenkins/plugins/bfa/CauseManagement/index.groovy
Labels: chore

#157 Adapt to Token Macro's new escapeHtml parameter
  pom.xml
  src/main/java/com/sonyericsson/jenkins/plugins/bfa/tokens/Renderer.java
  src/main/java/com/sonyericsson/jenkins/plugins/bfa/tokens/Token.java
  src/main/resources/com/sonyericsson/jenkins/plugins/bfa/tokens/Token/help.groovy
  src/test/java/com/sonyericsson/jenkins/plugins/bfa/tokens/TokenTest.java
Labels: bug, chore, documentation

#156 Export some fields about the found failure cause indication
  src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/FoundFailureCause.java
  src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/indication/FoundIndication.java
Labels: enhancement
